version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    ports:
      - "${API_PORT}:9000"
      - "${CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data

  nginx:
    build:
      context: ./nginx
    container_name: custom-nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - minio

volumes:
  minio_data:
